services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INTERNAL_API_URL: http://api:3001
    environment:
      NODE_ENV: production
      INTERNAL_API_URL: http://api:3001
    depends_on:
      - api
    ports:
      - 3000:3000

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000,http://web:3000
    expose:
      - 3001
