version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - procurement-network
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Karingani@1
      DB_NAME: procuremes-agent-test
    depends_on:
      - db
    networks:
      - procurement-network

  

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: procurement_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Karingani@1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - procurement-network

networks:
  procurement-network:
    driver: bridge